#!/bin/bash

#=================================================
#	查看整个集群的 jsp 进程
#
#	Version: 1.0.1
#	Author: Jack
#=================================================

## jpsall -h
# illegal argument: -h
# usage: jps [-help]
#        jps [-q] [-mlvV] [<hostid>]

# Definitions:
#     <hostid>:      <hostname>[:<port>]


# 参数
argument=$@

# 判断参数个数
if [[ $# > 1 ]] || [[ ! "$argument" =~ ^-.* ]]; then
  echo
  echo -e "\e[91m There is and can only be one parameter! \e[0m"
  echo
  exit 1
fi

# 从 /etc/hosts 文件获取集群 host
hosts=$(cat /etc/hosts | awk '$2!~/localhost/&&NF!=0{print $2}' | xargs)

# 遍历集群
for host in $hosts; do
  echo -e "\e[92m ============================== $host ============================== \e[0m"
  ssh $host jps $argument | grep -v 'Jps' | sort -k 2
done