#!/bin/bash

#=================================================
#	查看整个集群的 jsp 进程
#
#	Version: 1.0.0
#	Author: Jack
#=================================================

# 从 /etc/hosts 文件获取集群 host
hosts=$(cat /etc/hosts | awk '$2!~/localhost/&&NF!=0{print $2}' | xargs)

# 遍历集群
for host in $hosts; do
  echo -e "\e[92m ============================== $host ============================== \e[0m"
  ssh $host jps | grep -v 'Jps' | sort -k 2
done