#!/bin/bash

#=================================================
#	同步命令执行脚本
#
#	Version: 1.0.0
#	Author: Jack
#=================================================

command=$@

# 判断参数个数
if [ $# -lt 1 ]; then
  echo
  echo -e "\e[91m Not enough parameters! \e[0m"
  echo
  exit 1
fi

# 获取当前登录用户
user=`whoami`

# 获取当前所在的目录
curr_dir=$PWD

# 从 /etc/hosts 文件获取集群 host
hosts=$(cat /etc/hosts | awk '$2!~/localhost/&&NF!=0{print $2}' | xargs)

# 遍历集群
for host in $hosts; do
  echo -e "\e[92m ============================== $host ============================== \e[0m"
  ssh $user@$host "cd $curr_dir ; $command"
done