#!/bin/bash

#=================================================
#	集群文件批量分发脚本 rsync
#
#	Version: 1.0.0
#	Author: Jack
#=================================================

files=$@

# 判断参数个数
if [ $# -lt 1 ]; then
  echo
  echo -e "\e[91m Not enough parameters! \e[0m"
  echo
  exit 1
fi

# 判断 rsync 是否安装，如果没有安装则执行安装命令
if ! [ -x "`command -v rsync`" ]; then
    yum install -y rsync
fi

# 从 /etc/hosts 文件获取集群 host
hosts=$(cat /etc/hosts | awk '$2!~/localhost/&&NF!=0{print $2}' | xargs)

# 遍历集群
for host in $hosts; do

  echo -e "\e[92m ============================== $host ============================== \e[0m"
    # 遍历所有目录逐个发送
    for file in $files; do

      # 判断文件是否存在
      if [ -e $file ]; then

        # 获取父级目录
        pdir=$(cd -P $(dirname $file); pwd)

        # 获取当前文件的名称
        f_name=$(basename $file)

        ssh $host "mkdir -p $pdir"
        rsync -avl $pdir/$f_name $host:$pdir

      else
        echo
        echo -e "\e[91m $file does not exists! \e[0m"
        echo
      fi

    done

done
