#!/bin/bash

#=======================================================================================================================
#	同步命令执行脚本
#
#	Version: 1.0.0
#	Author: Jack
#=======================================================================================================================

# 自定义 hosts (例如: 'hadoop101,hadoop102,hadoop103')
customize_hosts=''

# 外部参数
command=$@

# 判断参数个数
if [[ $# < 1 ]]; then
  echo
  echo -e "\e[91m Not enough parameters! \e[0m"
  echo
  exit 1
fi

# 获取当前登录用户
user=`whoami`

# 获取当前所在的目录
current_dir=$PWD

# 如果自定义的 hosts 变量为空, 那就从 /etc/hosts 文件中获取集群 hosts
hosts=$(echo $customize_hosts | tr ',' ' ')

if [[ $(echo $hosts | wc -w) == 0 ]]; then
  hosts=$(cat /etc/hosts | awk '$2!~/localhost/&&NF!=0{print $2}' | xargs)
fi

# 遍历集群并执行命令
for host in $hosts; do
  echo -e "\e[92m ============================== $host ============================== \e[0m"
  ssh $user@$host "cd $current_dir ; $command"
done